
 # NOMBRE: Juan Carlos Muñoz Fernández
 # DNI: 28981062G
 # GRUPO: PB2

CC = cc

pruebaDispersion: dispersion.c dispersion.h pruebaDispersion.c
	$(CC) -g dispersion.c pruebaDispersion.c -o pruebaDispersion

limpiar:
	rm pruebaDispersion